### ISSUE TITLE
Assert panic on debug run

### ISSUE THREAD

**Issue by qm3ster** [XavilPergis/Rustel#8]
Crashes after rendering only background on every debug run.
Every time it's the assert at line 160:
https://github.com/XavilPergis/Notcraft/blob/13376fb891fd6a4f18d8bda6c886b4f31f2012b9/src/engine/world/chunk.rs#L156-L165

https://pastebin.com/rRC8AHL6

Didn't notice anything suspicious on `--release` run where that assert is skipped.

**Comment by XavilPergis** [comment]
This should be fixed because `PaddedChunk` no longer exists :P
